name = "Gakked Pack"
author = "xNygmatic"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf6de04ee2ff4ac5688146c3c57eb98f9ea163ed05d8f40467fd1108743d3551"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
