name = "Gakked Pack"
author = "xNygmatic"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac0dd1463215a6ffe05c77a0bebd8f47ffa6d0d2bb98f4a23089f2c4cda8ef2a"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
