name = "Gakked Pack"
author = "xNygmatic"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a503920e08192fdb58981e0c1a251118274f3a1fe79b7ab2b9fd60e96eda4cdc"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
